# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
product_key: chef-server

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-server-notify

automate:
  organization: products
  project: chef-server

github:
  release_branch:
    - master:
        # we'll have to bump this later, as globs won't let us do > 18
        version_constraint: "12.19.*"
    - 12-18-stable:
        # this branch should only be active 
        version_constraint: "12.18.*"
  # The file where the MAJOR.MINOR.PATCH version is kept. The version in this file
  # is bumped automatically via the `built_in:bump_version` merge_action.
  version_file: "VERSION"
  # The file where our CHANGELOG is kept. This file is updated automatically with
  # details from the Pull Request via the `built_in:update_changelog` merge_action.
  changelog_file: "CHANGELOG.md"

# Habitat + Docker exporting
habitat_packages:
  - openresty-noroot:
      source: src/openresty-noroot
      bldr_paths: src/openresty-noroot/*
  - oc-id:
      source: src/oc-id
      bldr_paths: src/oc-id/*
      export:
        - docker
  - chef-server-nginx:
      source: src/nginx
      bldr_paths: src/nginx/*
      export:
        - docker
  - bookshelf:
      source: src/bookshelf
      bldr_paths: src/bookshelf/*
      export:
        - docker
  - chef-server-ctl:
      source: src/chef-server-ctl
      bldr_paths: src/chef-server-ctl/*
      export:
        - docker
  - oc_bifrost:
      source: src/oc_bifrost
      bldr_paths: src/oc_bifrost/*
      export:
        - docker
  - oc_erchef:
      source: src/oc_erchef
      bldr_paths: src/oc_erchef/*
      export:
        - docker

# These actions are taken, in order they are specified, anytime a Pull Request is merged.
merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Version: Skip Bump"
        - "Expeditor: Skip All"
        - "Expeditor: ACC Only"
  - built_in:update_changelog:
      ignore_labels:
        - "Changelog: Skip Update"
        - "Expeditor: Skip All"
        - "Expeditor: ACC Only"
  - built_in:trigger_omnibus_build:
      ignore_labels:
        - "Omnibus: Skip Build"
        - "Expeditor: Skip All"
        - "Expeditor: ACC Only"
      only_if: built_in:bump_version
  - built_in:trigger_habitat_package_build:
      ignore_labels:
        - "Omnibus: Skip Build"
        - "Expeditor: Skip All"
        - "Expeditor: ACC Only"
      only_if: built_in:bump_version
  - built_in:update_acc:
      only_if_labels:
        - "Expeditor: ACC Only"

# Subscription to workload action of pull request merge to master branch on
# omnibus-software project will allow us to trigger an uncached omnibus build
# for chef-server when the omnibus-software has modified software config files.
subscriptions:
  # chef/omnibus-software
  - workload: pull_request_merged:chef/omnibus-software:master:*
    actions:
      - built_in:trigger_omnibus_expcache_build:
          only_if_modified:
            - config/software/*
# These actions are taken, in the order specified, when an Omnibus artifact is promoted
# within Chef's internal artifact storage system.
#
# TODO: add promoted_to_unstable action to update changelog with modified omnibus components
artifact_actions:
  promoted_to_unstable:
    - built_in:update_acc
  promoted_to_current:
  promoted_to_stable:
    - built_in:rollover_changelog
    - built_in:notify_chefio_slack_channels
